# Site settings
site_name: Low Carb London
title: London's Low carb, paleo friendly Supper Club
email:
description: London's Low carb, paleo friendly, clean eating Supper Club

landing_caption: Being a health foodie in London just got better
landing_caption_btn: Tell me more

app_cta_title: Discover what all the buzz is about!
app_cta_subtext: Our app will be available to download soon! Register now to be the first to get it!

top_picks_title: What's on the menu
top_picks_subtext: A few of our favourites you might find on the menu

features_title: What you can expect from our Supper Club
features_subtext: 
features_feature_1_title: Free from
features_feature_1_subtext: Almost everything we serve is dairy free, egg free and always refinded sugar, gluten & soy free - any questions, just ask!
features_feature_2_title: No vegetable oils
features_feature_2_subtext: We use coconut or avocado oil to cook with - no nasty surprises here!
features_feature_3_title: Guilt-free
features_feature_3_subtext: That heavy feeling you get in your stomach after leaving a restaurant?  Yeah, you don't get that here 🕺
features_feature_4_title: We LOVE food
features_feature_4_subtext: Maybe even more than you 😛

social_banner: Stay in touch

aside_title: Don't miss the chance to attend
aside_btn_text: Register your interest today!

lightbox_title: Sign up today!
lightbox_text: Give us your best email & we'll keep you posted on the next event is!

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "/" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: "UA-113891181-1"
addthis_id: #ra-5644da281510c62f
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/lowcarbldn
  - title: instagram
    url: https://instagram.com/lowcarbldn
  - title: facebook
    url: https://facebook.com/lowcarbldn
  - title: envelope
    url: mailto:rob+lcl@lowcarbrob.com
  #- title: youtube
  #  url: https://youtube.com/lowcarbldn
  #- title: google-plus
  #  url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: 
 - jekyll-paginate
#  - jekyll-feed
# Build settings
